#!/bin/bash
# file: killall
sudo killall -9 sh
sudo killall -9 node
sudo killall -9 ng
sudo killall -9 npm
sudo killall -9 socat
kill -9 $(lsof -t -i:3000)
kill -9 $(lsof -t -i:4200)
kill -9 $(lsof -t -i:80)

